name: tarlan_payments
description: "TarlanPayments Flutter SDK Project"
version: 0.0.1

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_svg: ^0.22.0
  provider: ^6.1.2
  flutter_inappwebview: ^6.0.0
  pretty_http_logger: ^1.0.3
  tarlan_transaction_generator:
    path: ../tarlan_transaction_generator
  flutter_file_downloader: ^1.2.1
  share_plus: ^9.0.0
  mask_text_input_formatter: ^2.9.0
  pointycastle: ^3.9.1
  encrypt: ^5.0.3

  crypto: any
  flutter_localizations:
    sdk: flutter
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mastercard_logo.svg
    - assets/placeholder_logo.png
    - assets/visa_logo.svg
    - assets/tarlan_logo.svg
    - assets/pci_logo.svg
    - assets/ic_warning.svg
    - assets/ic_success.svg
    - assets/ic_error.svg
    - assets/ic_delete.svg
    - assets/ic_cross.svg
    - assets/ic_confirm.svg
    - assets/ic_clock.svg
